name: CI/CD Expo App

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  # Firebase environment variables for builds
  EXPO_PUBLIC_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
  EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
  EXPO_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
  EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
  EXPO_PUBLIC_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./mobile

      - name: Lint code
        run: npm run lint
        working-directory: ./mobile
        continue-on-error: true

      - name: Type check
        run: npm run typecheck
        working-directory: ./mobile
        continue-on-error: true

      - name: Run tests
        run: npm test -- --passWithNoTests
        working-directory: ./mobile
        continue-on-error: true

      - name: Build Expo app (web)
        run: npm run build:web
        working-directory: ./mobile
        continue-on-error: true

      # Note: EAS builds removed - add EXPO_TOKEN later when ready for mobile builds

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./mobile

      - name: Audit dependencies for vulnerabilities
        run: npm audit --audit-level=moderate
        working-directory: ./mobile
        continue-on-error: true

      - name: Check for outdated dependencies
        run: npm outdated
        working-directory: ./mobile
        continue-on-error: true

  codeql-analysis:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and test Docker image
        run: |
          docker build -t yeti-consult-app:test ./mobile
          docker run --rm yeti-consult-app:test npm test -- --passWithNoTests || true

# Security Best Practices:
# - Store all secrets (API keys, tokens) in GitHub repository secrets, not in code or .env files.
# - Never echo or print secrets in logs.
# - Use branch protection rules to require passing checks before merging.
# - Review audit and CodeQL results regularly.
# - Firebase environment variables should be added to GitHub secrets for builds.
# - Add EXPO_TOKEN later when ready for mobile app builds. 